# Generated by Django 4.1.7 on 2023-10-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLine',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='location.tbllocation')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('monitor_mode', models.IntegerField()),
                ('monitor_status', models.IntegerField(blank=True, null=True)),
                ('back_color', models.IntegerField(blank=True, null=True)),
                ('back_image', models.CharField(blank=True, max_length=256, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStation',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='location.tbllocation')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('name_en', models.CharField(blank=True, max_length=32, null=True)),
                ('diagram', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('cross_station_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTrain',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='location.tbllocation')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('head_control_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('tail_control_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('head_lcd_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('tail_lcd_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('cars', models.IntegerField(blank=True, null=True)),
                ('head_camera_num', models.IntegerField(blank=True, null=True)),
                ('body_camera_num', models.IntegerField(blank=True, null=True)),
                ('pantograph_num', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_train',
                'managed': False,
            },
        ),
    ]
