# Generated by Django 4.1.7 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('host_device_id', models.IntegerField(blank=True, null=True)),
                ('line_id', models.IntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('mac', models.CharField(blank=True, max_length=20, null=True)),
                ('resolution', models.CharField(blank=True, max_length=32, null=True)),
                ('life_cycle', models.IntegerField(blank=True, null=True)),
                ('power_device', models.IntegerField(blank=True, null=True)),
                ('power_num', models.IntegerField(blank=True, null=True)),
                ('service_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('software_version', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor_flag', models.IntegerField(blank=True, null=True)),
                ('line_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('host', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_device_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location_type',
                'managed': False,
            },
        ),
    ]
