# Generated by Django 4.1.7 on 2023-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('bk_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(max_length=64)),
                ('op_level', models.IntegerField()),
                ('status', models.IntegerField()),
                ('login_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('login_status', models.IntegerField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('password_wrong_num', models.IntegerField()),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
    ]
