# Generated by Django 4.1.7 on 2023-04-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblFunctionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=64, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('func_type', models.IntegerField(blank=True, null=True)),
                ('component', models.CharField(blank=True, max_length=64, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_function_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_location_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('type', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('bk_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('op_level', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('login_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('login_status', models.IntegerField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('password_wrong_num', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRoleFunctionRel',
            fields=[
                ('function', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.tblfunctionpermission')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_role_function_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRoleLocationRel',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.tblrole')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_role_location_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserRoleRel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.tbluser')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_role_rel',
                'managed': False,
            },
        ),
    ]
